# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel_no', models.CharField(blank=True, max_length=20, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ordered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('requested_delivery_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.ClientPurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(max_length=20)),
                ('delivery_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientPurchaseRequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.ClientPurchaseRequest')),
            ],
        ),
        migrations.CreateModel(
            name='MPLPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_no', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('ordered_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('requested_delivery_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('actual_delivery_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=1)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MPLPurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.MPLPurchaseOrder')),
            ],
        ),
        migrations.CreateModel(
            name='MPLQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(blank=True, max_length=20, null=True)),
                ('quotation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=1)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.Client')),
                ('client_purchase_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.ClientPurchaseRequest')),
            ],
        ),
        migrations.CreateModel(
            name='MPLQuotationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(blank=True, max_length=20, null=True)),
                ('quotation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=1)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierQuotationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('part_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('supplier_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.SupplierQuotation')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
        migrations.AddField(
            model_name='mplquotationitem',
            name='supplier_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpl.SupplierQuotation'),
        ),
        migrations.AddField(
            model_name='mplpurchaseorder',
            name='supplier_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.SupplierQuotation'),
        ),
        migrations.AddField(
            model_name='clientpurchaseorder',
            name='mpl_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.MPLQuotation'),
        ),
    ]
