# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpl', '0002_auto_20181029_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientpurchaseorder',
            options={'verbose_name': 'Client Purchase Order', 'verbose_name_plural': 'Client Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='clientpurchaserequest',
            options={'verbose_name': 'Client Purchase Request', 'verbose_name_plural': 'Client Purchase Requests'},
        ),
        migrations.AlterModelOptions(
            name='mplpurchaseorder',
            options={'verbose_name': 'MPL Purchase Order', 'verbose_name_plural': 'MPL Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='mplquotation',
            options={'verbose_name': 'MPL Quotation', 'verbose_name_plural': 'MPL Quotations'},
        ),
        migrations.AlterModelOptions(
            name='supplierquotation',
            options={'verbose_name': 'Supplier Quotation', 'verbose_name_plural': 'Supplier Quotations'},
        ),
        migrations.RemoveField(
            model_name='mplquotationitem',
            name='supplier_quotation',
        ),
        migrations.AddField(
            model_name='mplquotationitem',
            name='mpl_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpl.MPLQuotation'),
        ),
    ]
