# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpl', '0005_auto_20181107_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplpurchaseorder',
            name='client_purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.ClientPurchaseOrder'),
        ),
    ]
