# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mpl', '0008_auto_20181107_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpurchaseorder',
            name='mpl_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.MPLQuotation'),
        ),
        migrations.AlterField(
            model_name='mplpurchaseorder',
            name='client_purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.ClientPurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='mplpurchaseorder',
            name='supplier_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.SupplierQuotation'),
        ),
        migrations.AlterField(
            model_name='mplquotation',
            name='client_purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mpl.ClientPurchaseRequest'),
        ),
    ]
