# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpl', '0010_mplpurchaseorderitem_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='mplquotationitem',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
